version: '3'

services:
  app:
    build: app/
    logging:
      options:
        max-size: "50M"
        max-file: "2"
    restart: always
    ports:
      - '8081:8081'
    environment:
      - 'HOST_URL=http://localhost:8081'
      - DB_URL=tarantool
      - DB_PORT=3301
    depends_on:
      - tarantool
    volumes:
      - ./app/media/:/usr/src/app/media/

  tarantool:
    build: tarantool/
    ports:
      - '3301:3301'
    volumes:
      - ./tarantool_data/:/var/lib/tarantool