version: '3'

services:
  app:
    build: app/
    logging:
      options:
        max-size: "50M"
        max-file: "2"
    restart: always
    environment:
      - 'HOST_URL=${HOST_URL}'
      - 'DB_URL=tarantool'
      - 'DB_PORT=3301'
    depends_on:
      - tarantool
    volumes:
      - ./app/media/:/usr/src/app/media/
    env_file:
      .env

  tarantool:
    build: tarantool/
    volumes:
      - ./tarantool_data/:/var/lib/tarantool
  nginx:
    build: ./nginx
    logging:
      options:
        max-size: '200M'
        max-file: '4'
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./app/media:/usr/src/app/media/